question_data = [
    {"text": "Linus Torvalds created Linux and Git.", "answer": "True"},
    {"text": "The logo for Snapchat is a Bell.", "answer": "False"},
    {"text": "Pointers were not used in the original C programming language; they were added later on in C++.",
     "answer": "False"},
    {"text": "&quot;HTML&quot; stands for Hypertext Markup Language.", "answer": "True"},
    {"text": "In most programming languages, the operator ++ is equivalent to the statement &quot;+= 1&quot;.",
     "answer": "True"},
    {"text": "Time on Computers is measured via the EPOX System.", "answer": "False"},
    {"text": "The Windows 7 operating system has six main editions.",
     "answer": "True"},
    {"text": "The NVidia GTX 1080 gets its name because it can only render at a 1920x1080 screen resolution.",
     "answer": "False"},
    {"text": "Linux was first created as an alternative to Windows XP.", "answer": "False"},
    {"text": "The Python programming language gets its name from the British comedy group &quot;Monty Python.&quot;",
     "answer": "True"}]
